[global]

# ---- Boundary clock settings ----

clock_type                     BC
boundary_clock_jbod            1

# ---- PTP transport ----

network_transport              UDPv4
delay_mechanism                E2E
time_stamping                  hardware

# ---- Timing / servo ----

domainNumber                   0
step_threshold                 0.00002
tx_timestamp_timeout           30
summary_interval               3

# ---- BMCA ----

priority1                      128
priority2                      128
clockClass                     128
clockAccuracy                  0x31
offsetScaledLogVariance        0xFFFF
slaveOnly                      0

logAnnounceInterval            1
logSyncInterval                0
logMinDelayReqInterval         0
announceReceiptTimeout         3

# ----------------------------------------------------------------------------

# Upstream port (slave)

# ----------------------------------------------------------------------------

[enp7s0]

# ----------------------------------------------------------------------------

# Downstream port (master to cameras)

# ----------------------------------------------------------------------------

[enp5s0]
masterOnly                     1
